# Generated by Django 4.0.6 on 2022-07-25 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SYSControl', '0006_alter_database_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_key', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
