# Generated by Django 4.0.6 on 2022-07-26 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SYSControl', '0008_alter_database_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Организация')),
            ],
        ),
        migrations.CreateModel(
            name='EnteryDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStart', models.TimeField(verbose_name='Начало')),
                ('timeEnd', models.TimeField(verbose_name='Окончание')),
                ('hourForPay', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Часов к оплате')),
                ('descriptionForClient', models.TextField(verbose_name='Описание для клиента')),
                ('descriptionNotForClient', models.TextField(verbose_name='Описание не дляклиента')),
            ],
        ),
        migrations.CreateModel(
            name='HeadDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата создания')),
                ('distance', models.BooleanField(verbose_name='Удаленно')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HeadDataBase_key', to='SYSControl.company', verbose_name='Организация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='HeadDataBase_key', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Сonfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Наименование конфигурации')),
            ],
        ),
        migrations.CreateModel(
            name='Сontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Организация')),
                ('cod', models.CharField(max_length=10, verbose_name='Код')),
                ('iin', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
            ],
        ),
        migrations.DeleteModel(
            name='DataBase',
        ),
        migrations.AddField(
            model_name='enterydatabase',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='EnteryDataBase_key', to='SYSControl.сonfiguration', verbose_name='Конфигурация'),
        ),
        migrations.AddField(
            model_name='enterydatabase',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='EnteryDataBase_key', to='SYSControl.сontractor', verbose_name='Контрагент'),
        ),
        migrations.AddField(
            model_name='enterydatabase',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EnteryDataBase_key', to='SYSControl.headdatabase', verbose_name='Шапка'),
        ),
    ]
