# Generated by Django 4.0.6 on 2022-07-27 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SYSControl', '0009_company_enterydatabase_headdatabase_сonfiguration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='сontractor',
            old_name='iin',
            new_name='inn',
        ),
    ]
