# Generated by Django 4.0.6 on 2022-08-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYSControl', '0010_rename_iin_сontractor_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='headdatabase',
            name='comment',
            field=models.CharField(default='', max_length=50, verbose_name='Комментарий'),
        ),
    ]
