# Generated by Django 4.0.6 on 2022-08-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SYSControl', '0011_headdatabase_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='headdatabase',
            name='chek',
            field=models.BooleanField(default=False, verbose_name='Проверено'),
        ),
    ]
